adding object models for location service along with documentation
RevatureRideShare/location-service pull request #2
Opened 2019-11-18 19:09 UTC by Astralvix

Any other grunt work will be done on this branch, then closed after approval of merging

2019-11-18 19:13 UTC, jurczakn requested changes

2019-11-18 19:13 UTC, jurczakn commented on src/main/java/com/revature/bean/HousingLocation.java
> +
unecessary white space

2019-11-19 14:18 UTC, Astralvix commented on src/main/java/com/revature/bean/HousingLocation.java
> +
all whitespace removed

2019-11-19 15:15 UTC, jurczakn approved these changes

2019-11-19 15:15 UTC, jurczakn commented
Good

2019-11-19 15:15 UTC, merged